export interface NPCI_TXN {
    NPCI_TXN_TYPE: string;
    NPCI_STATUS: string;
    TXNID: string;
    RRN: string | null;
    NPCI_CODE: any | null;
    DATE: string;
    TIME: string | null;
    AMOUNT: string | number;
    UMN: any;
    MAPID: any;
    INITMODE: any;
    PURPOSECODE: any;
    PAYERCODE: string | null;
    PAYERMCC: any;
    PAYER_VPA: string | null;
    PAYEECODE: any;
    PAYEEMCC: string | null;
    PAYEE_VPA: string;
    REMCODE: any;
    REM_IFSC_CODE: any;
    REM_ACC_TYPE: any;
    REM_ACC_NUMBER: any;
    BENCODE: any;
    BEN_IFSC_CODE: any;
    BEN_ACC_TYPE: any;
    BEN_ACC_NUMBER: any;
    LRN: any;
    RE1: any;
    RE2: any;
    RE3: any;
}